argo-cd:
  server:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=Prod,Tier=ArgoCD
  configs:
    params:
      server.basehref: /argocd/
      server.rootpath: '/argocd/'
    cm:
      url: https://a471f4a00f88f4bf6a95f892491d3ad2-467448411.ap-south-1.elb.amazonaws.com/argocd/
      dex.config: |
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23lisqRbcxcTl1EQkB
            clientSecret: 8de75f49ac0c285095f406199b2be242135ba3e7
            redirectURI: http://127.0.0.1:5556/argocd/dex/callback
            orgs:
            - name: CloudScope
              teams:
              - argo-admin
    rbac:
      policy.csv: |
        g, CloudScope:argo-admin, role:admin
