prometheus:
  server:
    alertmanager:
      enabled: true
      persistence:
        enabled: false
        size: 2Gi
        storageClass: gp2
    persistentVolume:
      enabled: true
      size: 8Gi
      annotations:
        volume.beta.kubernetes.io/storage-class: "gp2"
      storageClass: gp2
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=Prod,Tier=Grafana