grafana:
  adminUser: admin
  adminPassword: admin
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: "60"
    targetMemory: "70"
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: grafana-ini-config
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=Prod,Tier=Grafana

extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-ini-config
    data:
      grafana.ini: |-
        [server]
        domain = a5486dc8a59d442d5ad4273b62938dc8-353203771.ap-south-1.elb.amazonaws.com
        root_url = http://a5486dc8a59d442d5ad4273b62938dc8-353203771.ap-south-1.elb.amazonaws.com/grafana/
        serve_from_sub_path = true